# Generated by Django 2.1.5 on 2019-03-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autopost',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=200)),
                ('siteurl', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('posturl', models.CharField(default=None, max_length=200)),
                ('selection', models.CharField(default=None, max_length=100)),
                ('gettag', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
