# Generated by Django 2.1.5 on 2019-03-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autopost', '0002_auto_20190316_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopost',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
