# Generated by Django 2.1.5 on 2019-03-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autopost', '0003_auto_20190316_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='autopost',
            name='gettag',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='autopost',
            name='selection',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='autopost',
            name='title',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='autopost',
            name='posturl',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
